### ISSUE TITLE
Beginner Friendly Issue - Contact us Target Same Page

### ISSUE THREAD

**Issue by wimpywarlord** [wimpywarlord/BTech-Blueprint#1]
Hi,

👉  So I think you found this issue from the Beginner-friendly issues list, and you are just getting started with Open Source.

👉  This is a perfect opportunity to get your hand dirty, and not get overwhelmed at the same time. 

👉 I have deliberately introduced a bug into my website. 

💕 Problem 

The `contact`  button opens the hyperlink in a blank new page, I want it to open on the same page. 

![Screenshot_9](https://user-images.githubusercontent.com/41532804/135170860-7f87a421-22fd-439e-9449-97e65e8b03fe.png)

Kindly help me fix this 🥺.

💕Assistance

It's under the `views` folder, inside the `landing_page.ejs` file.

 💕How to contribute.
 
 Send a PR, and I review it. If it's up to the mark, I will approve it and merge it to the main codebase. 
 
 Learn how to send a PR [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by divyanshraj0408** [comment]
I would like to work on this issue, would love to have some assistance for the same.

**Comment by wimpywarlord** [comment]
The issue has been assigned to @divyanshraj0408, his PR will be merged and then the issue will be closed.
