### ISSUE TITLE
[Bug] : scroll-top 🔼 and chat buttons are ovelaping.

### ISSUE THREAD

**Issue by bairwa25** [wimpywarlord/BTech-Blueprint#8]
I want to fix this :
![image](https://user-images.githubusercontent.com/43534798/135675841-6697031e-f014-4bf0-a2f0-101b8965c2fa.png)

After fixing it look like this:
![image](https://user-images.githubusercontent.com/43534798/135675949-f74744c6-3023-4f4f-95e4-bc5f26ca9fad.png)

@wimpywarlord can I work on this?

**Comment by wimpywarlord** [comment]
Yes surely go ahead. 

I will mark the issue as hacktoberfest and assign it to you
